### ISSUE TITLE
TextStyle vertical alignment map is wrong

### ISSUE THREAD

**Issue by sasensi** [amzn/sketch-constructor#112]
Hi, by working with your library, I noticed that the values it is returning for text vertical alignment are sometimes wrong.
I think that center and bottom are inverted.

https://github.com/amzn/sketch-constructor/blob/6766e673dfe391473e065f8837a8b7087459d2de/utils/maps.js#L52-L61

From what I observe when manually setting the values from Sketch, center is `1` and bottom is `2`.
Here is a Sketch file demonstrating this: [vertical-alignment.zip](https://github.com/amzn/sketch-constructor/files/4673667/vertical-alignment.zip)

**Comment by dbanksdesign** [comment]
Thanks for bringing this up. Once we figure out why our travis releases are broken we can get this fixed.

**Comment by L2jLiga** [comment]
@dbanksdesign seems like releases working now, any updates?

**Comment by dbanksdesign** [comment]
Just posted a CR, I can merge it in later today 😁
