### ISSUE TITLE
Enable BorderOption by default

### ISSUE THREAD

**Issue by kgoedecke** [amzn/sketch-constructor#12]
I was wondering if there is any reason why a BorderOption object is disabled by default?

https://github.com/amzn/sketch-constructor/blob/master/models/BorderOptions/BorderOptions.js#L65

I'd suggest we either make it enabled by default or add the isEnabled flag to the constructor. What do you think?

**Comment by dbanksdesign** [comment]
Hah, generally the answer to "is there any reason" for anything this repository right now is "probably not". How about lets do both? Enabled by default and add the flag to the constructor. If you want to post a PR I can merge it, or I can get to it as well. If possible, it would be nice to have unit tests as well for the classes moving forward. I know the unit tests are very sparse right now, but I want to have better tests moving forward. 

Thanks for bringing this up, I'm sure there are tons of other issues like this...

**Comment by kgoedecke** [comment]
@dbanksdesign Alright, I will take care of it today. I've been working quite a lot with the library in the past few days and saw a few other things, that I wouldn't mind discussing with you and potentially changing around. let's do thisssss 🤓

**Comment by kgoedecke** [comment]
fixed in https://github.com/amzn/sketch-constructor/pull/14
