### ISSUE TITLE
Error: End of data reached (data length = 0, asked index = 4) when calling fromFIle

### ISSUE THREAD

**Issue by phil-isaacs** [amzn/sketch-constructor#121]
I have a node script that I'm using to grab symbols from a downloaded sketch file.

`const sketchFileData = await Sketch.fromFile(sketchFile); `

Everytime I run this code I get the same error  `Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?`

The file is there and I can open it but I can't seem to use this this function to query the data in it.

**Comment by dbanksdesign** [comment]
Could you post the sketch file? And have you tried doing that with a different sketch file and it works?

**Comment by phil-isaacs** [comment]
Opps, sorry I forgot I open this ticket. I was able to resolve it. It turned out to be an issue with another conflicting library. I will close this.

**Comment by Koshub** [comment]
@phil-isaacs I have the same issue, could you please share the solution?

**Comment by phil-isaacs** [comment]
> @phil-isaacs I have the same issue, could you please share the solution?

Hey @Koshub,

I believe it was a conflict with another existing library I was using. The problem is, I was using a so many other packages with this one that I'm not sure which one exactly it was anymore. Sorry I wish I could be more help. But I believe once I updated the conflicting package and did a reinstall this issue went away.

Phil

**Comment by Koshub** [comment]
@phil-isaacs Thank you

**Comment by dbanksdesign** [comment]
@Koshub do you still need help?

**Comment by Koshub** [comment]
@dbanksdesign no. Thank you. Well, it would be nice if you check [this one](https://github.com/amzn/sketch-constructor/issues/139), please. 🙂
