### ISSUE TITLE
Make the do_objectID consistent when created from a Sketch file 

### ISSUE THREAD

**Issue by Means88** [amzn/sketch-constructor#18]
When I call `Sketch.fromFile`, the `do_objectID` of layers are different from the ids in sketch file.

This is a part of `__tests__/__sketch-files/test.sketch`
```json
{
    "_class": "artboard",
    "do_objectID": "5863D14C-8C6E-4C73-801F-A5BF691CF415",
}
```

```js
it('should have the same do_objectID', () => {
  return Sketch.fromFile(`${process.cwd()}/__tests__/__sketch-files/test.sketch`).then(sketch => {
    const artboard = sketch.getPage('Page 1').getArtboard('Artboard');
    expect(artboard.do_objectID).toBe('5863D14C-8C6E-4C73-801F-A5BF691CF415');
  });
});
```

However it fails with

```
    expect(received).toBe(expected) // Object.is equality

    Expected: "5863D14C-8C6E-4C73-801F-A5BF691CF415"
    Received: "6F31FB28-DDF1-4AA5-A8DA-6946E3B1DF48"
```

The `do_objectID` was regenerated every time there.

https://github.com/amzn/sketch-constructor/blob/678ef236f41e7d17e31fa0984b7915fe7124cd84/models/Artboard/Artboard.js#L42

I want to do some modifications and write it back. It will cause some problems if the `do_objectID` is not consistent when integrating with other tools.
There might be an option to keep the `do_objectID`, or some ways to create the objects other than constructor.

**Comment by dbanksdesign** [comment]
Interesting, this is definitely a bug. What I tried to do is when working from an existing file to not modify any properties. That line you linked in Artboard.js should only run if it is constructed dynamically. The lines above:

```javascript
    super(args, json);
    if (!json) {
```

`json` here should be passed to the constructor if it is coming from a file. So there must be a bug in how we call the Artboard's constructor inside `Sketch.fromFile`....

**Comment by dbanksdesign** [comment]
Ah ok I think I found it.. 

https://github.com/amzn/sketch-constructor/blob/678ef236f41e7d17e31fa0984b7915fe7124cd84/utils/layerToClass.js#L31

That line should change to

```javascript
return new strToClass[layer._class](null, layer);
```

**Comment by dbanksdesign** [comment]
PR coming in hot 🔥
