### ISSUE TITLE
How to export artboard as png, svg and jpeg with options?

### ISSUE THREAD

**Issue by muuvmuuv** [amzn/sketch-constructor#37]
Is it possible to export an Artboard or part of it as SVG, PNG and JPEG? I would like to auto generate assets for my project. I just see that there is a `exportOptions` in Artboard obj but I can't see how to actually get the base64 image or something similiar.

**Comment by dbanksdesign** [comment]
That is a gooooood question. I don't know how to do that without actually running Sketch somehow..

**Comment by muuvmuuv** [comment]
Oh, that's a shame 😄 this would be sooo great. I'll contact the Sketch support to make this happen

**Comment by AvenirZheng** [comment]
needed in emergence

**Comment by muuvmuuv** [comment]
@AvenirZheng haven't got any response from Sketch. I just noticed that Sketch has their own API/Package. I don't have time to dig deeper into it but maybe you?

https://developer.sketch.com/reference/api/#export

**Comment by AvenirZheng** [comment]
we are trying to use sketch-cli to export image, but neither sketch-cli or Sketch Plugin API, it rely on Sketch APP.

https://developer.sketch.com/cli/export-assets

**Comment by dbanksdesign** [comment]
Yea unfortunately this would only be possible with the sketch-cli as the artboards and layers are in their proprietary JSON structure. We could create something that would take the Sketch models and translate into SVG, but that would be a huge project to map everything to the proper SVG tags. But if we did that, you could use something like [inkscape](https://www.npmjs.com/package/inkscape) to render a PNG from the SVG.

**Comment by muuvmuuv** [comment]
I'll close this then. Will use the CLI for the moment and wait for Sketch to implement an API for it.
