### ISSUE TITLE
Feature Request: support image model

### ISSUE THREAD

**Issue by coolzilj** [amzn/sketch-constructor#39]
I can't find image model in the source codes.

**Comment by dbanksdesign** [comment]
I'll take a look into it this week!

**Comment by filipux** [comment]
What is the status on this feature request? Would be great to have image support.

**Comment by dbanksdesign** [comment]
Will be coming really soon! Probably this week, we have a PR open right now: #48

**Comment by coolzilj** [comment]
Since #48 is merged, I think this issue is good to close now.
