### ISSUE TITLE
BUG: Sketch constructor arg for user should be `args.user` not `args.use`

### ISSUE THREAD

**Issue by SebastianFlo** [amzn/sketch-constructor#47]
Small typo here https://github.com/amzn/sketch-constructor/blob/v1.4.1/models/Sketch/Sketch.js#L53

`user: new User(args.use),`

should be 

`user: new User(args.user),`

**Comment by kgoedecke** [comment]
@SebastianFlo Since it's a small bug, do you mind putting up a PR for this?
