### ISSUE TITLE
Setting overrides for SymbolInstances via createInstance and update functions

### ISSUE THREAD

**Issue by diana-wang** [amzn/sketch-constructor#60]
Currently, there seems to be no easy way to set overrideValues on a SymbolInstance. Would it be useful to update createInstance to take in a list of overrides and/or create functions to update existing symbol instances?

**CreateInstance**

One way of updating createInstance is to pass in an array of override names and values.

```
var instance = this.symbolMaster.createInstance({
    name: name,
    overrideValues: [
      {
        name: "swatch.value",
        value: sketch.getLayerStyle(styleName)
      },
      {
        name: "token.name",
        value: name
      },
      {
        name: "hex.value",
        value: hex
      },
      {
        name: "rgba.value",
        value: rgba
      }
    ]
  });
```
For Objects like Styles that aren't stored in SymbolMaster, do_objectID is used as the value for the resulting OverrideValue. It would be nice to just pass in the name on the object, rather than the whole object, but there would be no way for the function to access the layer styles to fetch the ID
```
{
        name: "swatch.value",
        value: styleName
},
```

**Update Functions**

It may also be useful to have functions that update overrides for existing SymbolInstances. For example:

```
this.symbolMaster.updateInstance(instance, name, value);
```

If this is something that's desired, I have working examples of both of the above, which I can clean up and put in a PR. 

<del>It also includes a very basic implementation of a class for OverrideValue</del>(will be moved to a different pull request - too big scope)

**Comment by dbanksdesign** [comment]
That would be awesome! I think that both of those would be amazing to have. If you'd like to open a PR that would be great. Thank you!

**Comment by diana-wang** [comment]
Will do!

Though actually, I may move this functionality into Document instead. As it is now, nested overrides and Layer Styles won't work properly, but Document has access to everything it should need, which would be a lot nicer. If we want to keep the additional functionality in CreateInstance(), that can stay - otherwise, it may be better just to keep that function simple.

**Comment by diana-wang** [comment]
PR #63
