### ISSUE TITLE
Add a helper for resizing functionality

### ISSUE THREAD

**Issue by jorgecasar** [amzn/sketch-constructor#97]
Resizing functionality is a bit weird and it's very useful having a helper to avoid calculate the value over and over.

There are a good post about [Reverse engineering Sketch’s resizing functionality](https://medium.com/zendesk-engineering/reverse-engineering-sketchs-resizing-functionality-23f6aae2da1a) to understand how it works.

**Comment by dbanksdesign** [comment]
@jorgecasar can we close this out with the resizingConstraint API you added or do you think there is more?

**Comment by jorgecasar** [comment]
Yes, this issue could be closed by PR #99
